#제목과 버전 설정
application:
   version: v0.0.1
   title: HYUNSANGWON

#MyBatis 설정
mybatis:
   mapper-locations: classpath:/sqlmap/sqlmapper_*.xml
   type-aliases-package: com.dw.board.vo
   
#MySQL 접속정보 설정
spring:
   datasource:
      initialization-mode: NEVER
      schema: classpath:init.sql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dw?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: tkddnjs0823
   #JSP 경로 설정
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
      #css,js,image 폴더 위치 설정
      static-path-pattern: /resources/static/**
      
pagehelper:
   #helper-dialect: 사용할 데이터베이스
   helper-dialect: mysql
   #reasonable : 0페이지 요청이들어오면 자동으로 1페이지로, 13페이지 까지 있는데 14페이지 요청이 들어오면 자동으로 13페이지로 변환.    
   reasonable: true

      
      
      